
#ifndef CONSTANTS_IS_DEF
#define CONSTANTS_IS_DEF


#define WIN_WIDTH   1920
#define WIN_HEIGHT  1080

#define MAP_WIDTH 40
#define MAP_HEIGHT 30

#define BLOCK_SIZE 64
#define BLOCK_NUMBER 8

#define MARIO_SPEED 4
#define MARIO_JUMP_IMPULSE -22
#define MISSILE_SPEED 6

#define DECAL 8 * BLOCK_SIZE

#define RIGHT_LIMIT_SCROLLING WIN_WIDTH - DECAL
#define LEFT_LIMIT_SCROLLING  DECAL

#define RIGHT_MAP_LIMIT BLOCK_SIZE * (MAP_WIDTH - 1)
#define LEFT_MAP_LIMIT 0

#define LEFT 1
#define RIGHT 0

#define RANDMAX = 1280



#endif
