
#ifndef CONSTANTS_IS_DEF
#define CONSTANTS_IS_DEF


#define WIN_WIDTH   1280
#define WIN_HEIGHT  768

#define MAP_WIDTH 30
#define MAP_HEIGHT 30

#define BLOCK_SIZE 64

#define MARIO_SPEED 4

#define RIGHT_LIMIT_SCROLLING WIN_WIDTH*0.8
#define LEFT_LIMIT_SCROLLING WIN_WIDTH*0.2

#define RIGHT_MAP_LIMIT MAP_WIDTH * BLOCK_SIZE - BLOCK_SIZE
#define LEFT_MAP_LIMIT 0

#define LEFT 1
#define RIGHT 0

#define RANDMAX = 1280



#endif
